import { createFileRoute } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { ContentPage, AnswerSection } from "@/components/content-page";
import { breadcrumbSchema, pageHead } from "@/lib/site";

export const Route = createFileRoute("/nomera")({ head: () => ({ ...pageHead("Номера и цены Luxx Aparts в Алматы", "Общие и отдельные комнаты Luxx Aparts в Алматы. Уточните свободные места и актуальную цену напрямую у администратора.", "/nomera"), scripts: [{ type: "application/ld+json", children: JSON.stringify(breadcrumbSchema("Номера и цены", "/nomera")) }] }), component: RoomsPage });
function RoomsPage() { return <ContentPage eyebrow="Номера и цены" title="Какой вариант размещения выбрать?" intro="В Luxx Aparts доступны два формата: общие комнаты для гостей, которым важна практичная стоимость, и отдельные комнаты для большей приватности. Точный состав свободных вариантов, количество кроватей и стоимость на нужные даты администратор подтверждает перед бронированием.">
  <AnswerSection title="Какие комнаты доступны?"><div className="grid gap-4 sm:grid-cols-2"><article className="border border-border p-6"><h3 className="font-display text-xl font-semibold text-foreground">Общие комнаты</h3><p className="mt-3">Размещение с отдельным спальным местом в общей комнате. Количество мест, тип кровати и доступность на выбранные даты уточняются у администратора.</p></article><article className="border border-border p-6"><h3 className="font-display text-xl font-semibold text-foreground">Отдельные комнаты</h3><p className="mt-3">Приватный вариант размещения. Вместимость, площадь, санузел и конфигурацию кроватей администратор подтвердит для доступного номера.</p></article></div></AnswerSection>
  <AnswerSection title="Сколько стоит ночь?"><p>Актуальная цена зависит от формата комнаты, дат и срока проживания. Luxx Aparts подтверждает стоимость до бронирования по телефону или в WhatsApp; на сайте цена не указана, чтобы гость не получил устаревший тариф. Спросите администратора о стоимости на конкретные даты и возможных условиях длительного проживания.</p></AnswerSection>
  <AnswerSection title="Что доступно гостям?"><ul className="mt-5 grid gap-3 sm:grid-cols-2">{["Wi‑Fi", "Коворкинг-зона", "Заселение 24/7", "Общие и отдельные комнаты"].map(x => <li key={x} className="flex items-center gap-3 text-foreground"><Check className="size-4 text-primary" />{x}</li>)}</ul></AnswerSection>
</ContentPage>; }