/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BronirovanieRouteImport } from './routes/bronirovanie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FotoRouteImport } from './routes/foto'
import { Route as HostelNaMesyacRouteImport } from './routes/hostel-na-mesyac'
import { Route as HostelRyadomSAvtovokzalomSayranRouteImport } from './routes/hostel-ryadom-s-avtovokzalom-sayran'
import { Route as KakDobratsyaRouteImport } from './routes/kak-dobratsya'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as OtzyvyRouteImport } from './routes/otzyvy'
import { Route as PravilaRouteImport } from './routes/pravila'
import { Route as RyadomRouteImport } from './routes/ryadom'
import { Route as UdobstvaRouteImport } from './routes/udobstva'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogAvtorRouteImport } from './routes/blog.avtor'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAmenitiesRouteImport } from './routes/en/amenities'
import { Route as EnBookingRouteImport } from './routes/en/booking'
import { Route as EnContactsRouteImport } from './routes/en/contacts'
import { Route as EnFaqRouteImport } from './routes/en/faq'
import { Route as EnHouseRulesRouteImport } from './routes/en/house-rules'
import { Route as EnHowToGetThereRouteImport } from './routes/en/how-to-get-there'
import { Route as EnRoomsRouteImport } from './routes/en/rooms'
import { Route as NomeraIndexRouteImport } from './routes/nomera.index'
import { Route as NomeraTypeRouteImport } from './routes/nomera.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BronirovanieRoute = BronirovanieRouteImport.update({
  id: '/bronirovanie',
  path: '/bronirovanie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoRoute = FotoRouteImport.update({
  id: '/foto',
  path: '/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelNaMesyacRoute = HostelNaMesyacRouteImport.update({
  id: '/hostel-na-mesyac',
  path: '/hostel-na-mesyac',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRyadomSAvtovokzalomSayranRoute =
  HostelRyadomSAvtovokzalomSayranRouteImport.update({
    id: '/hostel-ryadom-s-avtovokzalom-sayran',
    path: '/hostel-ryadom-s-avtovokzalom-sayran',
    getParentRoute: () => rootRouteImport,
  } as any)
const KakDobratsyaRoute = KakDobratsyaRouteImport.update({
  id: '/kak-dobratsya',
  path: '/kak-dobratsya',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OtzyvyRoute = OtzyvyRouteImport.update({
  id: '/otzyvy',
  path: '/otzyvy',
  getParentRoute: () => rootRouteImport,
} as any)
const PravilaRoute = PravilaRouteImport.update({
  id: '/pravila',
  path: '/pravila',
  getParentRoute: () => rootRouteImport,
} as any)
const RyadomRoute = RyadomRouteImport.update({
  id: '/ryadom',
  path: '/ryadom',
  getParentRoute: () => rootRouteImport,
} as any)
const UdobstvaRoute = UdobstvaRouteImport.update({
  id: '/udobstva',
  path: '/udobstva',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAvtorRoute = BlogAvtorRouteImport.update({
  id: '/blog/avtor',
  path: '/blog/avtor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAmenitiesRoute = EnAmenitiesRouteImport.update({
  id: '/en/amenities',
  path: '/en/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/en/booking',
  path: '/en/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactsRoute = EnContactsRouteImport.update({
  id: '/en/contacts',
  path: '/en/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/en/faq',
  path: '/en/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHouseRulesRoute = EnHouseRulesRouteImport.update({
  id: '/en/house-rules',
  path: '/en/house-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHowToGetThereRoute = EnHowToGetThereRouteImport.update({
  id: '/en/how-to-get-there',
  path: '/en/how-to-get-there',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoomsRoute = EnRoomsRouteImport.update({
  id: '/en/rooms',
  path: '/en/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeraIndexRoute = NomeraIndexRouteImport.update({
  id: '/nomera/',
  path: '/nomera/',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeraTypeRoute = NomeraTypeRouteImport.update({
  id: '/nomera/$type',
  path: '/nomera/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/foto': typeof FotoRoute
  '/hostel-na-mesyac': typeof HostelNaMesyacRoute
  '/hostel-ryadom-s-avtovokzalom-sayran': typeof HostelRyadomSAvtovokzalomSayranRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/avtor': typeof BlogAvtorRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/en/amenities': typeof EnAmenitiesRoute
  '/en/booking': typeof EnBookingRoute
  '/en/contacts': typeof EnContactsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/house-rules': typeof EnHouseRulesRoute
  '/en/how-to-get-there': typeof EnHowToGetThereRoute
  '/en/rooms': typeof EnRoomsRoute
  '/nomera/$type': typeof NomeraTypeRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/nomera/': typeof NomeraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/foto': typeof FotoRoute
  '/hostel-na-mesyac': typeof HostelNaMesyacRoute
  '/hostel-ryadom-s-avtovokzalom-sayran': typeof HostelRyadomSAvtovokzalomSayranRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/avtor': typeof BlogAvtorRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/en/amenities': typeof EnAmenitiesRoute
  '/en/booking': typeof EnBookingRoute
  '/en/contacts': typeof EnContactsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/house-rules': typeof EnHouseRulesRoute
  '/en/how-to-get-there': typeof EnHowToGetThereRoute
  '/en/rooms': typeof EnRoomsRoute
  '/nomera/$type': typeof NomeraTypeRoute
  '/blog': typeof BlogIndexRoute
  '/en': typeof EnIndexRoute
  '/nomera': typeof NomeraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/foto': typeof FotoRoute
  '/hostel-na-mesyac': typeof HostelNaMesyacRoute
  '/hostel-ryadom-s-avtovokzalom-sayran': typeof HostelRyadomSAvtovokzalomSayranRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/avtor': typeof BlogAvtorRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/en/amenities': typeof EnAmenitiesRoute
  '/en/booking': typeof EnBookingRoute
  '/en/contacts': typeof EnContactsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/house-rules': typeof EnHouseRulesRoute
  '/en/how-to-get-there': typeof EnHowToGetThereRoute
  '/en/rooms': typeof EnRoomsRoute
  '/nomera/$type': typeof NomeraTypeRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/nomera/': typeof NomeraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/foto'
    | '/hostel-na-mesyac'
    | '/hostel-ryadom-s-avtovokzalom-sayran'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/llms-full.txt'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
    | '/blog/$slug'
    | '/blog/avtor'
    | '/blog/rss.xml'
    | '/en/amenities'
    | '/en/booking'
    | '/en/contacts'
    | '/en/faq'
    | '/en/house-rules'
    | '/en/how-to-get-there'
    | '/en/rooms'
    | '/nomera/$type'
    | '/blog/'
    | '/en/'
    | '/nomera/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/foto'
    | '/hostel-na-mesyac'
    | '/hostel-ryadom-s-avtovokzalom-sayran'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/llms-full.txt'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
    | '/blog/$slug'
    | '/blog/avtor'
    | '/blog/rss.xml'
    | '/en/amenities'
    | '/en/booking'
    | '/en/contacts'
    | '/en/faq'
    | '/en/house-rules'
    | '/en/how-to-get-there'
    | '/en/rooms'
    | '/nomera/$type'
    | '/blog'
    | '/en'
    | '/nomera'
  id:
    | '__root__'
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/foto'
    | '/hostel-na-mesyac'
    | '/hostel-ryadom-s-avtovokzalom-sayran'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/llms-full.txt'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
    | '/blog/$slug'
    | '/blog/avtor'
    | '/blog/rss.xml'
    | '/en/amenities'
    | '/en/booking'
    | '/en/contacts'
    | '/en/faq'
    | '/en/house-rules'
    | '/en/how-to-get-there'
    | '/en/rooms'
    | '/nomera/$type'
    | '/blog/'
    | '/en/'
    | '/nomera/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BronirovanieRoute: typeof BronirovanieRoute
  FaqRoute: typeof FaqRoute
  FotoRoute: typeof FotoRoute
  HostelNaMesyacRoute: typeof HostelNaMesyacRoute
  HostelRyadomSAvtovokzalomSayranRoute: typeof HostelRyadomSAvtovokzalomSayranRoute
  KakDobratsyaRoute: typeof KakDobratsyaRoute
  KontaktyRoute: typeof KontaktyRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  OtzyvyRoute: typeof OtzyvyRoute
  PravilaRoute: typeof PravilaRoute
  RyadomRoute: typeof RyadomRoute
  UdobstvaRoute: typeof UdobstvaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAvtorRoute: typeof BlogAvtorRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  EnAmenitiesRoute: typeof EnAmenitiesRoute
  EnBookingRoute: typeof EnBookingRoute
  EnContactsRoute: typeof EnContactsRoute
  EnFaqRoute: typeof EnFaqRoute
  EnHouseRulesRoute: typeof EnHouseRulesRoute
  EnHowToGetThereRoute: typeof EnHowToGetThereRoute
  EnRoomsRoute: typeof EnRoomsRoute
  NomeraTypeRoute: typeof NomeraTypeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  NomeraIndexRoute: typeof NomeraIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronirovanie': {
      id: '/bronirovanie'
      path: '/bronirovanie'
      fullPath: '/bronirovanie'
      preLoaderRoute: typeof BronirovanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto': {
      id: '/foto'
      path: '/foto'
      fullPath: '/foto'
      preLoaderRoute: typeof FotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel-na-mesyac': {
      id: '/hostel-na-mesyac'
      path: '/hostel-na-mesyac'
      fullPath: '/hostel-na-mesyac'
      preLoaderRoute: typeof HostelNaMesyacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel-ryadom-s-avtovokzalom-sayran': {
      id: '/hostel-ryadom-s-avtovokzalom-sayran'
      path: '/hostel-ryadom-s-avtovokzalom-sayran'
      fullPath: '/hostel-ryadom-s-avtovokzalom-sayran'
      preLoaderRoute: typeof HostelRyadomSAvtovokzalomSayranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kak-dobratsya': {
      id: '/kak-dobratsya'
      path: '/kak-dobratsya'
      fullPath: '/kak-dobratsya'
      preLoaderRoute: typeof KakDobratsyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otzyvy': {
      id: '/otzyvy'
      path: '/otzyvy'
      fullPath: '/otzyvy'
      preLoaderRoute: typeof OtzyvyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravila': {
      id: '/pravila'
      path: '/pravila'
      fullPath: '/pravila'
      preLoaderRoute: typeof PravilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ryadom': {
      id: '/ryadom'
      path: '/ryadom'
      fullPath: '/ryadom'
      preLoaderRoute: typeof RyadomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udobstva': {
      id: '/udobstva'
      path: '/udobstva'
      fullPath: '/udobstva'
      preLoaderRoute: typeof UdobstvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/avtor': {
      id: '/blog/avtor'
      path: '/blog/avtor'
      fullPath: '/blog/avtor'
      preLoaderRoute: typeof BlogAvtorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/amenities': {
      id: '/en/amenities'
      path: '/en/amenities'
      fullPath: '/en/amenities'
      preLoaderRoute: typeof EnAmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/en/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contacts': {
      id: '/en/contacts'
      path: '/en/contacts'
      fullPath: '/en/contacts'
      preLoaderRoute: typeof EnContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/en/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/house-rules': {
      id: '/en/house-rules'
      path: '/en/house-rules'
      fullPath: '/en/house-rules'
      preLoaderRoute: typeof EnHouseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/how-to-get-there': {
      id: '/en/how-to-get-there'
      path: '/en/how-to-get-there'
      fullPath: '/en/how-to-get-there'
      preLoaderRoute: typeof EnHowToGetThereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/rooms': {
      id: '/en/rooms'
      path: '/en/rooms'
      fullPath: '/en/rooms'
      preLoaderRoute: typeof EnRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomera/': {
      id: '/nomera/'
      path: '/nomera'
      fullPath: '/nomera/'
      preLoaderRoute: typeof NomeraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomera/$type': {
      id: '/nomera/$type'
      path: '/nomera/$type'
      fullPath: '/nomera/$type'
      preLoaderRoute: typeof NomeraTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BronirovanieRoute: BronirovanieRoute,
  FaqRoute: FaqRoute,
  FotoRoute: FotoRoute,
  HostelNaMesyacRoute: HostelNaMesyacRoute,
  HostelRyadomSAvtovokzalomSayranRoute: HostelRyadomSAvtovokzalomSayranRoute,
  KakDobratsyaRoute: KakDobratsyaRoute,
  KontaktyRoute: KontaktyRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  OtzyvyRoute: OtzyvyRoute,
  PravilaRoute: PravilaRoute,
  RyadomRoute: RyadomRoute,
  UdobstvaRoute: UdobstvaRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAvtorRoute: BlogAvtorRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  EnAmenitiesRoute: EnAmenitiesRoute,
  EnBookingRoute: EnBookingRoute,
  EnContactsRoute: EnContactsRoute,
  EnFaqRoute: EnFaqRoute,
  EnHouseRulesRoute: EnHouseRulesRoute,
  EnHowToGetThereRoute: EnHowToGetThereRoute,
  EnRoomsRoute: EnRoomsRoute,
  NomeraTypeRoute: NomeraTypeRoute,
  BlogIndexRoute: BlogIndexRoute,
  EnIndexRoute: EnIndexRoute,
  NomeraIndexRoute: NomeraIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
