/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BronirovanieRouteImport } from './routes/bronirovanie'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as KakDobratsyaRouteImport } from './routes/kak-dobratsya'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as NomeraRouteImport } from './routes/nomera'
import { Route as OtzyvyRouteImport } from './routes/otzyvy'
import { Route as PravilaRouteImport } from './routes/pravila'
import { Route as RyadomRouteImport } from './routes/ryadom'
import { Route as UdobstvaRouteImport } from './routes/udobstva'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BronirovanieRoute = BronirovanieRouteImport.update({
  id: '/bronirovanie',
  path: '/bronirovanie',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KakDobratsyaRoute = KakDobratsyaRouteImport.update({
  id: '/kak-dobratsya',
  path: '/kak-dobratsya',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const NomeraRoute = NomeraRouteImport.update({
  id: '/nomera',
  path: '/nomera',
  getParentRoute: () => rootRouteImport,
} as any)
const OtzyvyRoute = OtzyvyRouteImport.update({
  id: '/otzyvy',
  path: '/otzyvy',
  getParentRoute: () => rootRouteImport,
} as any)
const PravilaRoute = PravilaRouteImport.update({
  id: '/pravila',
  path: '/pravila',
  getParentRoute: () => rootRouteImport,
} as any)
const RyadomRoute = RyadomRouteImport.update({
  id: '/ryadom',
  path: '/ryadom',
  getParentRoute: () => rootRouteImport,
} as any)
const UdobstvaRoute = UdobstvaRouteImport.update({
  id: '/udobstva',
  path: '/udobstva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/nomera': typeof NomeraRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/nomera': typeof NomeraRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bronirovanie': typeof BronirovanieRoute
  '/faq': typeof FaqRoute
  '/kak-dobratsya': typeof KakDobratsyaRoute
  '/kontakty': typeof KontaktyRoute
  '/nomera': typeof NomeraRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pravila': typeof PravilaRoute
  '/ryadom': typeof RyadomRoute
  '/udobstva': typeof UdobstvaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/nomera'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/nomera'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
  id:
    | '__root__'
    | '/'
    | '/bronirovanie'
    | '/faq'
    | '/kak-dobratsya'
    | '/kontakty'
    | '/nomera'
    | '/otzyvy'
    | '/pravila'
    | '/ryadom'
    | '/udobstva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BronirovanieRoute: typeof BronirovanieRoute
  FaqRoute: typeof FaqRoute
  KakDobratsyaRoute: typeof KakDobratsyaRoute
  KontaktyRoute: typeof KontaktyRoute
  NomeraRoute: typeof NomeraRoute
  OtzyvyRoute: typeof OtzyvyRoute
  PravilaRoute: typeof PravilaRoute
  RyadomRoute: typeof RyadomRoute
  UdobstvaRoute: typeof UdobstvaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronirovanie': {
      id: '/bronirovanie'
      path: '/bronirovanie'
      fullPath: '/bronirovanie'
      preLoaderRoute: typeof BronirovanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kak-dobratsya': {
      id: '/kak-dobratsya'
      path: '/kak-dobratsya'
      fullPath: '/kak-dobratsya'
      preLoaderRoute: typeof KakDobratsyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomera': {
      id: '/nomera'
      path: '/nomera'
      fullPath: '/nomera'
      preLoaderRoute: typeof NomeraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otzyvy': {
      id: '/otzyvy'
      path: '/otzyvy'
      fullPath: '/otzyvy'
      preLoaderRoute: typeof OtzyvyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pravila': {
      id: '/pravila'
      path: '/pravila'
      fullPath: '/pravila'
      preLoaderRoute: typeof PravilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ryadom': {
      id: '/ryadom'
      path: '/ryadom'
      fullPath: '/ryadom'
      preLoaderRoute: typeof RyadomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udobstva': {
      id: '/udobstva'
      path: '/udobstva'
      fullPath: '/udobstva'
      preLoaderRoute: typeof UdobstvaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BronirovanieRoute: BronirovanieRoute,
  FaqRoute: FaqRoute,
  KakDobratsyaRoute: KakDobratsyaRoute,
  KontaktyRoute: KontaktyRoute,
  NomeraRoute: NomeraRoute,
  OtzyvyRoute: OtzyvyRoute,
  PravilaRoute: PravilaRoute,
  RyadomRoute: RyadomRoute,
  UdobstvaRoute: UdobstvaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
